---
- name: Prepare the server
  hosts: all
  gather_facts: no

  tasks:
  - name: Download the 7-Zip package
    win_get_url:
      url: https://www.7-zip.org/a/7z1701-x64.msi
      dest: C:\Windows\Temp\7z.msi
