---
- name: Prepare the server
  hosts: all
  remote_user: root
  vars:
    - fqdn: www.untouchable.com

  tasks:
  - name: Install Apache
    apt: name=apache2 update_cache=yes state=latest

  - name: Create the webserver Document Root
    ansible.builtin.file:
      path: "/var/www/html/{{ fqdn }}/public"
      state: directory
      mode: '0755' 

  - name: Place a demo landing page.
    copy:
       src: files/index.html
       dest: "/var/www/html/{ fqdn }}public/index.html"
      owner: root
      group: root
      mode: 0644

  - name: Create a basic Website landing page.
    template:
       src: vhost.conf.j2
       dest: "/etc/apache2/sites-available/{ fqdn }}.conf"
       mode: 0644
       owner: root
       group: root
       
  - name: Create a symbolic link
    ansible.builtin.file:
      src: "/etc/apache2/sites-available/{ fqdn }}.conf"
      dest: "/etc/apache2/sites-enabled/{ fqdn }}.conf"
      owner: root
      group: root
      state: link

  - name: Restart service apache2
    ansible.builtin.service:
      name: apache2
      state: restarted

