---
- name: Prepare the server
  hosts: all
  remote_user: root
  vars:
    - fqdn: www.untouchable.com

  tasks:
  - name: Install Apache
    apt: name=apache2 update_cache=yes state=started

  - name: Create the webserver Document Root
    ansible.builtin.file:
      path: "/var/www/html/{{ fqdn }}/public"
      owner: apache
      group: apache
      mode: '1644' 

  - name: Create a basic Website landing page.
    template:
       src: vhost.conf.j2
       dest: /etc/apache2/sites-enabled/{ fqdn }}.conf"
       mode: 0644
       owner: root
       group: root
    notify:
      - restart_apache2

  handlers:
  - name: restart_apache2
    service:
      name: apache2
      state: restart
      enabled: yes

