---
- name: Prepare the server
  hosts: all
  remote_user: root
  vars:
    - fqdn: www.untouchable.com

  tasks:
  - name: Install Apache
    apt: name=apache2 update_cache=yes state=started

  - name: Create a basic Website landing page.
    template:
       src: vhost.conf.j2
       dest: /var/www/html/{{ fqdn }}.conf"
       mode: 0644
       owner: root
       group: root
